spring:
  application:
    name: gym-system

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gymdb
    username: gym
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  security:
    jwt:
      secret: randomSecretKeyForJWT
      expiration-ms: 3600000 # 1 hour
    bruteForce:
      maxAttempts: 3
      blockDurationMs: 300000 # 5 minutes
  cors:
    allowed-origins: "http://localhost:3000"
  cloud:
    discovery:
      enabled: false

management:
  health:
    jms:
      enabled: ${app.jms.enabled:false}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# yaml
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: false
    fetchRegistry: false
  instance:
    preferIpAddress: false

app:
  jms:
    enabled: false
    broker-url: tcp://localhost:61616
    queue:
      workload-update: workload.update